name: keycash_offline
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.2.3
  go_router: ^14.2.7
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.0.0
  intl: ^0.20.2
  flutter_spinkit: ^5.2.1
  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.9.1

  # NUEVAS dependencias para base de datos local/offline
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  uuid: ^4.5.1

  # Este paquete se usa en la app (no solo en tests)
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true